-- ============================================================================
-- km_engine — PostgreSQL 16 — 001_init.sql
-- Baseline: work-plan §2.2 · requirements FR4/FR5/FR6/FR1 · ADR-002
-- Idempotente: CREATE TABLE IF NOT EXISTS + INSERT ... ON CONFLICT DO NOTHING
--              (ri-esecuzione sicura).
-- Nota: la tabella refresh_tokens non compare nel work-plan §2.2 ma è richiesta
--       da FR4.5 (revoca sessioni) in architettura stateless — vedere ADR-002 D1.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. IDENTITÀ — users / roles / user_roles / teams / user_teams
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    username      TEXT        NOT NULL UNIQUE,
    email         TEXT        NOT NULL UNIQUE,
    password_hash TEXT        NOT NULL,                    -- argon2id (fallback bcrypt) — ADR-002 D5
    active        BOOLEAN     NOT NULL DEFAULT TRUE,       -- false = revoca globale (FR4.5)
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS roles (
    id          SMALLINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        TEXT        NOT NULL UNIQUE
                            CHECK (name IN ('admin', 'editor', 'viewer', 'ingestor')),  -- 4 ruoli baseline (Q1)
    description TEXT
);

-- Seed dei 4 ruoli (idempotente)
INSERT INTO roles (id, name, description) VALUES
    (1, 'admin',    'Gestione sistema, utenti, ruoli, backup, risoluzione conflitti'),
    (2, 'editor',   'Lettura + scrittura su scope autorizzato'),
    (3, 'viewer',   'Solo lettura su scope autorizzato'),
    (4, 'ingestor', 'Servizio: pipeline automatica di ingestione, nessun accesso UI')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id SMALLINT NOT NULL REFERENCES roles (id) ON DELETE RESTRICT,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    granted_by UUID REFERENCES users (id) ON DELETE SET NULL,
    PRIMARY KEY (user_id, role_id)                       -- un utente può avere più ruoli (ADR-002 D2)
);

CREATE TABLE IF NOT EXISTS teams (
    id          SMALLINT   PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        TEXT       NOT NULL UNIQUE,              -- es. "Team Engineering" (Q1)
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_teams (
    user_id UUID     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    team_id SMALLINT NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, team_id)
);

-- ACL granulare opzionale (work-plan §2.2; non usata dal filtro di default nel MVP — ADR-002 D2)
CREATE TABLE IF NOT EXISTS permissions (
    id             BIGSERIAL PRIMARY KEY,
    user_id        UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    entity_pattern TEXT NOT NULL,                        -- pattern sull'id/label dell'entità del grafo
    access         TEXT NOT NULL CHECK (access IN ('read', 'write')),
    UNIQUE (user_id, entity_pattern, access)
);

-- ----------------------------------------------------------------------------
-- 2. SESSIONI — refresh_tokens (revoca, FR4.5 — ADR-002 D1)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  TEXT        NOT NULL UNIQUE,             -- hash del refresh token (mai il token in chiaro)
    issued_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,                             -- NULL = token attivo (rotazione ad ogni uso)
    revoked_by  UUID REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user    ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires ON refresh_tokens (expires_at);

-- ----------------------------------------------------------------------------
-- 3. AUDIT LOG — solo modifiche, append-only (FR5.2, Q9 — ADR-002 D4)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGSERIAL  PRIMARY KEY,
    user_id     UUID REFERENCES users (id) ON DELETE SET NULL,   -- NULL = azione di sistema (pipeline, migrazione)
    action      TEXT       NOT NULL,                    -- es. CREATE / UPDATE / INVALIDATE / RESOLVE / GRANT_ROLE
    entity_id   TEXT       NOT NULL,                    -- id dell'entità (grafo o Postgres)
    entity_type TEXT       NOT NULL,                    -- es. Fact / Entity / User / IngestJob / Conflict
    old_value   JSONB,                                  -- stato prima della modifica
    new_value   JSONB,                                  -- stato dopo la modifica
    ts          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_ts          ON audit_log (ts);
CREATE INDEX IF NOT EXISTS idx_audit_log_user        ON audit_log (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_entity      ON audit_log (entity_type, entity_id);

-- Append-only: l'utente applicativo non riceve grant di UPDATE/DELETE
-- (da applicare dopo la creazione del role applicativo, vedere db/README.md).

-- ----------------------------------------------------------------------------
-- 4. INGESTION — ingest_jobs (FR1.5: stato persistente e resume)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ingest_jobs (
    id          BIGSERIAL  PRIMARY KEY,
    source_uri  TEXT       NOT NULL,
    type        TEXT       NOT NULL CHECK (type IN ('code', 'document', 'image')),  -- Q3: no video/audio nel MVP
    status      TEXT       NOT NULL DEFAULT 'pending'
                           CHECK (status IN ('pending', 'running', 'paused', 'completed', 'failed')),
    progress    SMALLINT   NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    error       TEXT,
    created_by  UUID REFERENCES users (id) ON DELETE SET NULL,   -- account Ingestor (ADR-002 D2)
    started_at  TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ingest_jobs_status ON ingest_jobs (status);
CREATE INDEX IF NOT EXISTS idx_ingest_jobs_source ON ingest_jobs (source_uri);

-- ----------------------------------------------------------------------------
-- 5. CONFLICT CHECK — conflicts (FR6, Q10/Q11 — risoluzione manuale, solo Admin)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS conflicts (
    id          BIGSERIAL  PRIMARY KEY,
    entity_id   TEXT       NOT NULL,                    -- Entity del grafo (Neo4j) coinvolta
    property    TEXT       NOT NULL,                    -- proprietà/fatto in conflitto
    value_a     TEXT       NOT NULL,
    value_b     TEXT       NOT NULL,
    source_a    TEXT       NOT NULL,                    -- uri/id sorgente A
    source_b    TEXT       NOT NULL,                    -- uri/id sorgente B
    status      TEXT       NOT NULL DEFAULT 'pending'
                           CHECK (status IN ('pending', 'approved', 'rejected')),  -- FR6.2 workflow
    suggestion  TEXT,                                   -- Q10: suggerimento automatico (es. "B più recente di A")
    resolved_by UUID REFERENCES users (id) ON DELETE SET NULL,   -- Q11: solo Admin nel MVP
    resolved_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_conflicts_status ON conflicts (status);
CREATE INDEX IF NOT EXISTS idx_conflicts_entity ON conflicts (entity_id);
-- Storico delle risoluzioni (FR6.3): le righe non vengono mai cancellate,
-- il cambio di status è tracciato anche in audit_log.

COMMIT;

-- ============================================================================
-- VERIFICA (dopo l'applicazione):
--   \dt
--   SELECT name, description FROM roles ORDER BY id;
-- ============================================================================
